-- Add complete Judge0 language support
-- This migration adds all active and archived languages from Judge0

-- First, remove existing languages to avoid conflicts
TRUNCATE TABLE languages RESTART IDENTITY CASCADE;

-- Insert all active languages with exact Judge0 compatibility
INSERT INTO languages (id, name, compile_cmd, run_cmd, source_file, is_archived) VALUES

-- Active languages from Judge0
(43, 'Plain Text', NULL, '/bin/cat text.txt', 'text.txt', false),
(44, 'Executable', NULL, '/bin/chmod +x a.out && ./a.out', 'a.out', false),
(45, 'Assembly (NASM 2.14.02)', '/usr/local/nasm-2.14.02/bin/nasmld -f elf64 %s main.asm', './a.out', 'main.asm', false),
(46, 'Bash (5.0.0)', NULL, '/usr/local/bash-5.0/bin/bash script.sh', 'script.sh', false),
(47, 'Basic (FBC 1.07.1)', '/usr/local/fbc-1.07.1/bin/fbc %s main.bas', './main', 'main.bas', false),
(48, 'C (GCC 7.4.0)', '/usr/local/gcc-7.4.0/bin/gcc %s main.c', './a.out', 'main.c', false),
(49, 'C (GCC 8.3.0)', '/usr/local/gcc-8.3.0/bin/gcc %s main.c', './a.out', 'main.c', false),
(50, 'C (GCC 9.2.0)', '/usr/local/gcc-9.2.0/bin/gcc %s main.c', './a.out', 'main.c', false),
(51, 'C# (Mono 6.6.0.161)', '/usr/local/mono-6.6.0.161/bin/mcs %s Main.cs', '/usr/local/mono-6.6.0.161/bin/mono Main.exe', 'Main.cs', false),
(52, 'C++ (GCC 7.4.0)', '/usr/local/gcc-7.4.0/bin/g++ %s main.cpp', 'LD_LIBRARY_PATH=/usr/local/gcc-7.4.0/lib64 ./a.out', 'main.cpp', false),
(53, 'C++ (GCC 8.3.0)', '/usr/local/gcc-8.3.0/bin/g++ %s main.cpp', 'LD_LIBRARY_PATH=/usr/local/gcc-8.3.0/lib64 ./a.out', 'main.cpp', false),
(54, 'C++ (GCC 9.2.0)', '/usr/local/gcc-9.2.0/bin/g++ %s main.cpp', 'LD_LIBRARY_PATH=/usr/local/gcc-9.2.0/lib64 ./a.out', 'main.cpp', false),
(55, 'Common Lisp (SBCL 2.0.0)', NULL, 'SBCL_HOME=/usr/local/sbcl-2.0.0/lib/sbcl /usr/local/sbcl-2.0.0/bin/sbcl --script script.lisp', 'script.lisp', false),
(56, 'D (DMD 2.089.1)', '/usr/local/d-2.089.1/linux/bin64/dmd %s main.d', './main', 'main.d', false),
(57, 'Elixir (1.9.4)', NULL, '/usr/local/elixir-1.9.4/bin/elixir script.exs', 'script.exs', false),
(58, 'Erlang (OTP 22.2)', NULL, '/bin/sed -i ''1s/^/\\n/'' main.erl && /usr/local/erlang-22.2/bin/escript main.erl', 'main.erl', false),
(59, 'Fortran (GFortran 9.2.0)', '/usr/local/gcc-9.2.0/bin/gfortran %s main.f90', 'LD_LIBRARY_PATH=/usr/local/gcc-9.2.0/lib64 ./a.out', 'main.f90', false),
(60, 'Go (1.13.5)', 'GOCACHE=/tmp/.cache/go-build /usr/local/go-1.13.5/bin/go build %s main.go', './main', 'main.go', false),
(61, 'Haskell (GHC 8.8.1)', '/usr/local/ghc-8.8.1/bin/ghc %s main.hs', './main', 'main.hs', false),
(62, 'Java (OpenJDK 13.0.1)', '/usr/local/openjdk13/bin/javac %s Main.java', '/usr/local/openjdk13/bin/java Main', 'Main.java', false),
(63, 'JavaScript (Node.js 12.14.0)', NULL, '/usr/local/node-12.14.0/bin/node script.js', 'script.js', false),
(64, 'Lua (5.3.5)', '/usr/local/lua-5.3.5/luac53 %s script.lua', '/usr/local/lua-5.3.5/lua53 ./luac.out', 'script.lua', false),
(65, 'OCaml (4.09.0)', '/usr/local/ocaml-4.09.0/bin/ocamlc %s main.ml', './a.out', 'main.ml', false),
(66, 'Octave (5.1.0)', NULL, '/usr/local/octave-5.1.0/bin/octave-cli -q --no-gui --no-history script.m', 'script.m', false),
(67, 'Pascal (FPC 3.0.4)', '/usr/local/fpc-3.0.4/bin/fpc %s main.pas', './main', 'main.pas', false),
(68, 'PHP (7.4.1)', NULL, '/usr/local/php-7.4.1/bin/php script.php', 'script.php', false),
(69, 'Prolog (GNU Prolog 1.4.5)', 'PATH="/usr/local/gprolog-1.4.5/gprolog-1.4.5/bin:$PATH" /usr/local/gprolog-1.4.5/gprolog-1.4.5/bin/gplc --no-top-level %s main.pro', './main', 'main.pro', false),
(70, 'Python (2.7.17)', NULL, '/usr/local/python-2.7.17/bin/python2 script.py', 'script.py', false),
(71, 'Python (3.8.1)', NULL, '/usr/local/python-3.8.1/bin/python3 script.py', 'script.py', false),
(72, 'Ruby (2.7.0)', NULL, '/usr/local/ruby-2.7.0/bin/ruby script.rb', 'script.rb', false),
(73, 'Rust (1.40.0)', '/usr/local/rust-1.40.0/bin/rustc %s main.rs', './main', 'main.rs', false),
(74, 'TypeScript (3.7.4)', '/usr/bin/tsc %s script.ts', '/usr/local/node-12.14.0/bin/node script.js', 'script.ts', false),
(75, 'C (Clang 7.0.1)', '/usr/bin/clang-7 %s main.c', './a.out', 'main.c', false),
(76, 'C++ (Clang 7.0.1)', '/usr/bin/clang++-7 %s main.cpp', './a.out', 'main.cpp', false),
(77, 'COBOL (GnuCOBOL 2.2)', '/usr/local/gnucobol-2.2/bin/cobc -free -x %s main.cob', 'LD_LIBRARY_PATH=/usr/local/gnucobol-2.2/lib ./main', 'main.cob', false),
(78, 'Kotlin (1.3.70)', '/usr/local/kotlin-1.3.70/bin/kotlinc %s Main.kt', '/usr/local/kotlin-1.3.70/bin/kotlin MainKt', 'Main.kt', false),
(79, 'Objective-C (Clang 7.0.1)', '/usr/bin/clang-7 `gnustep-config --objc-flags | sed ''s/-W[^ ]* //g''` `gnustep-config --base-libs | sed ''s/-shared-libgcc//''` -I/usr/lib/gcc/x86_64-linux-gnu/8/include main.m %s', './a.out', 'main.m', false),
(80, 'R (4.0.0)', NULL, '/usr/local/r-4.0.0/bin/Rscript script.r', 'script.r', false),
(81, 'Scala (2.13.2)', '/usr/local/scala-2.13.2/bin/scalac %s Main.scala', '/usr/local/scala-2.13.2/bin/scala Main', 'Main.scala', false),
(82, 'SQL (SQLite 3.27.2)', NULL, '/bin/cat script.sql | /usr/bin/sqlite3 db.sqlite', 'script.sql', false),
(83, 'Swift (5.2.3)', '/usr/local/swift-5.2.3/bin/swiftc %s Main.swift', './Main', 'Main.swift', false),
(84, 'Visual Basic.Net (vbnc 0.0.0.5943)', '/usr/bin/vbnc %s Main.vb', '/usr/bin/mono Main.exe', 'Main.vb', false),
(85, 'Perl (5.28.1)', NULL, '/usr/bin/perl script.pl', 'script.pl', false),
(86, 'Clojure (1.10.1)', NULL, '/usr/local/bin/java -jar /usr/local/clojure-1.10.1/clojure.jar main.clj', 'main.clj', false),
(87, 'F# (.NET Core SDK 3.1.202)', NULL, 'mkdir -p ~/.dotnet && touch ~/.dotnet/3.1.202.dotnetFirstUseSentinel && /usr/local/dotnet-sdk/dotnet fsi script.fsx', 'script.fsx', false),
(88, 'Groovy (3.0.3)', '/usr/local/groovy-3.0.3/bin/groovyc %s script.groovy', '/usr/local/bin/java -cp ".:/usr/local/groovy-3.0.3/lib/*" script', 'script.groovy', false),
(89, 'Multi-file program', '', '/bin/true', 'main', false),

-- Archived languages from Judge0
(1, 'Bash (4.4)', NULL, '/usr/local/bash-4.4/bin/bash script.sh', 'script.sh', true),
(2, 'Bash (4.0)', NULL, '/usr/local/bash-4.0/bin/bash script.sh', 'script.sh', true),
(3, 'Basic (fbc 1.05.0)', '/usr/local/fbc-1.05.0/bin/fbc %s main.bas', './main', 'main.bas', true),
(4, 'C (gcc 7.2.0)', '/usr/local/gcc-7.2.0/bin/gcc %s main.c', './a.out', 'main.c', true),
(5, 'C (gcc 6.4.0)', '/usr/local/gcc-6.4.0/bin/gcc %s main.c', './a.out', 'main.c', true),
(6, 'C (gcc 6.3.0)', '/usr/local/gcc-6.3.0/bin/gcc %s main.c', './a.out', 'main.c', true),
(7, 'C (gcc 5.4.0)', '/usr/local/gcc-5.4.0/bin/gcc %s main.c', './a.out', 'main.c', true),
(8, 'C (gcc 4.9.4)', '/usr/local/gcc-4.9.4/bin/gcc %s main.c', './a.out', 'main.c', true),
(9, 'C (gcc 4.8.5)', '/usr/local/gcc-4.8.5/bin/gcc %s main.c', './a.out', 'main.c', true),
(10, 'C++ (g++ 7.2.0)', '/usr/local/gcc-7.2.0/bin/g++ %s main.cpp', 'LD_LIBRARY_PATH=/usr/local/gcc-7.2.0/lib64 ./a.out', 'main.cpp', true),
(11, 'C++ (g++ 6.4.0)', '/usr/local/gcc-6.4.0/bin/g++ %s main.cpp', 'LD_LIBRARY_PATH=/usr/local/gcc-6.4.0/lib64 ./a.out', 'main.cpp', true),
(12, 'C++ (g++ 6.3.0)', '/usr/local/gcc-6.3.0/bin/g++ %s main.cpp', 'LD_LIBRARY_PATH=/usr/local/gcc-6.3.0/lib64 ./a.out', 'main.cpp', true),
(13, 'C++ (g++ 5.4.0)', '/usr/local/gcc-5.4.0/bin/g++ %s main.cpp', 'LD_LIBRARY_PATH=/usr/local/gcc-5.4.0/lib64 ./a.out', 'main.cpp', true),
(14, 'C++ (g++ 4.9.4)', '/usr/local/gcc-4.9.4/bin/g++ %s main.cpp', 'LD_LIBRARY_PATH=/usr/local/gcc-4.9.4/lib64 ./a.out', 'main.cpp', true),
(15, 'C++ (g++ 4.8.5)', '/usr/local/gcc-4.8.5/bin/g++ %s main.cpp', 'LD_LIBRARY_PATH=/usr/local/gcc-4.8.5/lib64 ./a.out', 'main.cpp', true),
(16, 'C# (mono 5.4.0.167)', '/usr/local/mono-5.4.0.167/bin/mcs %s Main.cs', '/usr/local/mono-5.4.0.167/bin/mono Main.exe', 'Main.cs', true),
(17, 'C# (mono 5.2.0.224)', '/usr/local/mono-5.2.0.224/bin/mcs %s Main.cs', '/usr/local/mono-5.2.0.224/bin/mono Main.exe', 'Main.cs', true),
(18, 'Clojure (1.8.0)', NULL, '/usr/bin/java -cp /usr/local/clojure-1.8.0/clojure-1.8.0.jar clojure.main main.clj', 'main.clj', true),
(19, 'Crystal (0.23.1)', '/usr/local/crystal-0.23.1-3/bin/crystal build %s main.cr', './main', 'main.cr', true),
(20, 'Elixir (1.5.1)', NULL, '/usr/local/elixir-1.5.1/bin/elixir main.exs', 'main.exs', true),
(21, 'Erlang (OTP 20.0)', NULL, '/bin/sed -i "s/^/\\n/" main.erl && /usr/local/erlang-20.0/bin/escript main.erl', 'main.erl', true),
(22, 'Go (1.9)', '/usr/local/go-1.9/bin/go build %s main.go', './main', 'main.go', true),
(23, 'Haskell (ghc 8.2.1)', '/usr/local/ghc-8.2.1/bin/ghc %s main.hs', './main', 'main.hs', true),
(24, 'Haskell (ghc 8.0.2)', '/usr/local/ghc-8.0.2/bin/ghc %s main.hs', './main', 'main.hs', true),
(25, 'Insect (5.0.0)', NULL, '/usr/local/insect-5.0.0/insect main.ins', 'main.ins', true),
(26, 'Java (OpenJDK 9 with Eclipse OpenJ9)', '/usr/local/openjdk9-openj9/bin/javac %s Main.java', '/usr/local/openjdk9-openj9/bin/java Main', 'Main.java', true),
(27, 'Java (OpenJDK 8)', '/usr/lib/jvm/java-8-openjdk-amd64/bin/javac %s Main.java', '/usr/lib/jvm/java-8-openjdk-amd64/bin/java Main', 'Main.java', true),
(28, 'Java (OpenJDK 7)', '/usr/lib/jvm/java-7-openjdk-amd64/bin/javac %s Main.java', '/usr/lib/jvm/java-7-openjdk-amd64/bin/java Main', 'Main.java', true),
(29, 'JavaScript (nodejs 8.5.0)', NULL, '/usr/local/node-8.5.0/bin/node main.js', 'main.js', true),
(30, 'JavaScript (nodejs 7.10.1)', NULL, '/usr/local/node-7.10.1/bin/node main.js', 'main.js', true),
(31, 'OCaml (4.05.0)', '/usr/local/ocaml-4.05.0/bin/ocamlc %s main.ml', './a.out', 'main.ml', true),
(32, 'Octave (4.2.0)', NULL, '/usr/local/octave-4.2.0/bin/octave-cli -q --no-gui --no-history file.m', 'file.m', true),
(33, 'Pascal (fpc 3.0.0)', '/usr/local/fpc-3.0.0/bin/fpc %s main.pas', './main', 'main.pas', true),
(34, 'Python (3.6.0)', NULL, '/usr/local/python-3.6.0/bin/python3 main.py', 'main.py', true),
(35, 'Python (3.5.3)', NULL, '/usr/local/python-3.5.3/bin/python3 main.py', 'main.py', true),
(36, 'Python (2.7.9)', NULL, '/usr/local/python-2.7.9/bin/python main.py', 'main.py', true),
(37, 'Python (2.6.9)', NULL, '/usr/local/python-2.6.9/bin/python main.py', 'main.py', true),
(38, 'Ruby (2.4.0)', NULL, '/usr/local/ruby-2.4.0/bin/ruby main.rb', 'main.rb', true),
(39, 'Ruby (2.3.3)', NULL, '/usr/local/ruby-2.3.3/bin/ruby main.rb', 'main.rb', true),
(40, 'Ruby (2.2.6)', NULL, '/usr/local/ruby-2.2.6/bin/ruby main.rb', 'main.rb', true),
(41, 'Ruby (2.1.9)', NULL, '/usr/local/ruby-2.1.9/bin/ruby main.rb', 'main.rb', true),
(42, 'Rust (1.20.0)', '/usr/local/rust-1.20.0/bin/rustc %s main.rs', './main', 'main.rs', true);

-- Set sequence to continue from the highest ID
SELECT setval('languages_id_seq', (SELECT MAX(id) FROM languages));

INSERT INTO submission_constraints (id, number_of_runs, cpu_time_limit, cpu_extra_time, wall_time_limit, memory_limit, stack_limit, max_processes_and_or_threads, enable_per_process_and_thread_time_limit, enable_per_process_and_thread_memory_limit, max_file_size, compiler_options, command_line_arguments, redirect_stderr_to_stdout, callback_url, additional_files, enable_network) VALUES
(1, 1, 5.0, 1.0, 10.0, 128000, 64000, 60, false, false, 1024, NULL, NULL, false, NULL, NULL, false);